-- MySQL Script generated by MySQL Workbench
-- Fri Aug 26 10:36:33 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bravas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bravas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bravas` DEFAULT CHARACTER SET utf8 ;
USE `bravas` ;

-- -----------------------------------------------------
-- Table `bravas`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bravas`.`Users` ;

CREATE TABLE IF NOT EXISTS `bravas`.`Users` (
  `user_uuid` VARCHAR(36) NOT NULL,
  `user_name` VARCHAR(15) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(15) NOT NULL,
  `enabled` BOOLEAN NOT NULL DEFAULT 0,
  PRIMARY KEY (`user_uuid`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bravas`.`Groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bravas`.`Groups` ;

CREATE TABLE IF NOT EXISTS `bravas`.`Groups` (
  `group_uuid` VARCHAR(36) NOT NULL,
  `group_name` VARCHAR(45) NOT NULL,
  `pic` BLOB NULL,
  `description` VARCHAR(200) NULL,
  `owner` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`group_uuid`),
  UNIQUE INDEX `group_name_UNIQUE` (`group_name` ASC) VISIBLE,
  INDEX `fk_Group_Users2_idx` (`owner` ASC) VISIBLE,
  CONSTRAINT `fk_Group_Users2`
    FOREIGN KEY (`owner`)
    REFERENCES `bravas`.`Users` (`user_uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bravas`.`Groups_has_Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bravas`.`Groups_has_Users` ;

CREATE TABLE IF NOT EXISTS `bravas`.`Groups_has_Users` (
  `Users_idUsers` VARCHAR(36) NOT NULL,
  `Groups_idGroups` VARCHAR(36) NOT NULL,
  `isAdmin` BOOLEAN NOT NULL DEFAULT 0,
  PRIMARY KEY (`Users_idUsers`, `Groups_idGroups`),
  INDEX `fk_Groups_has_Users_Users1_idx` (`Users_idUsers` ASC) VISIBLE,
  INDEX `fk_Groups_has_Users_Groups1_idx` (`Groups_idGroups` ASC) VISIBLE,
  CONSTRAINT `fk_Groups_has_Users_Groups1`
    FOREIGN KEY (`Groups_idGroups`)
    REFERENCES `bravas`.`Groups` (`group_uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Groups_has_Users_Users1`
    FOREIGN KEY (`Users_idUsers`)
    REFERENCES `bravas`.`Users` (`user_uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bravas`.`Posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bravas`.`Posts` ;

CREATE TABLE IF NOT EXISTS `bravas`.`Posts` (
  `post_uuid` VARCHAR(36) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `date` DATETIME NOT NULL,
  `body` LONGTEXT NOT NULL,
  `Groups_idGroups` VARCHAR(36) NOT NULL,
  `Users_idUsers` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`post_uuid`),
  UNIQUE INDEX `idPosts_UNIQUE` (`post_uuid` ASC) VISIBLE,
  UNIQUE INDEX `title_UNIQUE` (`title` ASC) VISIBLE,
  INDEX `fk_Posts_Groups1_idx` (`Groups_idGroups` ASC) VISIBLE,
  INDEX `fk_Posts_Users1_idx` (`Users_idUsers` ASC) VISIBLE,
  CONSTRAINT `fk_Posts_Groups1`
    FOREIGN KEY (`Groups_idGroups`)
    REFERENCES `bravas`.`Groups` (`group_uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Posts_Users1`
    FOREIGN KEY (`Users_idUsers`)
    REFERENCES `bravas`.`Users` (`user_uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bravas`.`Comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bravas`.`Comments` ;

CREATE TABLE IF NOT EXISTS `bravas`.`Comments` (
  `comment_uuid` VARCHAR(36) NOT NULL,
  `comment_text` VARCHAR(45) NOT NULL,
  `date` DATETIME NOT NULL,
  `Users_idUsers` VARCHAR(36) NOT NULL,
  `Posts_idPosts` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`comment_uuid`),
  INDEX `fk_Comments_Users1_idx` (`Users_idUsers` ASC) VISIBLE,
  INDEX `fk_Comments_Posts1_idx` (`Posts_idPosts` ASC) VISIBLE,
  CONSTRAINT `fk_Comments_Users1`
    FOREIGN KEY (`Users_idUsers`)
    REFERENCES `bravas`.`Users` (`user_uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comments_Posts1`
    FOREIGN KEY (`Posts_idPosts`)
    REFERENCES `bravas`.`Posts` (`post_uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bravas`.`Likes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bravas`.`Likes` ;

CREATE TABLE IF NOT EXISTS `bravas`.`Likes` (
  `like_uuid` VARCHAR(36) NOT NULL,
  `Users_idUsers` VARCHAR(36) NOT NULL,
  `Posts_idPosts` VARCHAR(36) NOT NULL COMMENT 'indica si el ususario está autorizado o no',
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`like_uuid`),
  INDEX `fk_Likes_Users1_idx` (`Users_idUsers` ASC) VISIBLE,
  INDEX `fk_Likes_Posts1_idx` (`Posts_idPosts` ASC) VISIBLE,
  UNIQUE INDEX `like_id_UNIQUE` (`like_uuid` ASC) VISIBLE,
  CONSTRAINT `fk_Likes_Users1`
    FOREIGN KEY (`Users_idUsers`)
    REFERENCES `bravas`.`Users` (`user_uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Likes_Posts1`
    FOREIGN KEY (`Posts_idPosts`)
    REFERENCES `bravas`.`Posts` (`post_uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
